<?xml version="1.0" encoding="utf-8"?><Database Name="WebBuyPhone" Class="DBDataContext" xmlns="http://schemas.microsoft.com/linqtosql/dbml/2007">
  <Connection Mode="WebSettings" ConnectionString="Data Source=Admin;Initial Catalog=WebBuyPhone;User ID=sa;Connect Timeout=30;Encrypt=False;TrustServerCertificate=False" SettingsObjectName="System.Configuration.ConfigurationManager.ConnectionStrings" SettingsPropertyName="WebBuyPhoneConnectionString" Provider="System.Data.SqlClient" />
  <Table Name="dbo.AccountEmp" Member="AccountEmps">
    <Type Name="AccountEmp">
      <Column Name="ID_Account" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="ID_Emp" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Username" Type="System.String" DbType="VarChar(100)" CanBeNull="true" />
      <Column Name="Password" Type="System.String" DbType="VarChar(30)" CanBeNull="true" />
      <Column Name="Secret_Question" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Secret_Answer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Employee_AccountEmp" Member="Employee" ThisKey="ID_Emp" OtherKey="ID_Emp" Type="Employee" IsForeignKey="true" />
    </Type>
  </Table>
  <Table Name="dbo.Employees" Member="Employees">
    <Type Name="Employee">
      <Column Name="ID_Emp" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="FullName" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Address" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Email" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Phone" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Passport" Type="System.String" DbType="NVarChar(30)" CanBeNull="true" />
      <Column Name="Birthday" Type="System.DateTime" DbType="Date" CanBeNull="true" />
      <Column Name="Sex" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Employee_AccountEmp" Member="AccountEmps" ThisKey="ID_Emp" OtherKey="ID_Emp" Type="AccountEmp" />
    </Type>
  </Table>
  <Table Name="dbo.Manufacturer" Member="Manufacturers">
    <Type Name="Manufacturer">
      <Column Name="Id_Manufacturer" Type="System.String" DbType="NVarChar(100) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_Manufacturer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Association Name="Manufacturer_Product" Member="Products" ThisKey="Id_Manufacturer" OtherKey="ID_Manufacturer" Type="Product" />
    </Type>
  </Table>
  <Table Name="dbo.Products" Member="Products">
    <Type Name="Product">
      <Column Name="ID_Product" Type="System.String" DbType="NVarChar(200) NOT NULL" IsPrimaryKey="true" CanBeNull="false" />
      <Column Name="Name_Product" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="ID_Manufacturer" Type="System.String" DbType="NVarChar(100)" CanBeNull="true" />
      <Column Name="Price_Product" Type="System.Double" DbType="Float" CanBeNull="true" />
      <Column Name="Img_Product" Type="System.String" DbType="NVarChar(200)" CanBeNull="true" />
      <Column Name="Active" Type="System.Boolean" DbType="Bit" CanBeNull="true" />
      <Column Name="Newfeature" Type="System.String" DbType="NVarChar(1000)" CanBeNull="true" />
      <Column Name="Screen" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Operating" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="FrontCamera" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RearCamera" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="CPU" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="RAM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="InternalMemory" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="MemoryStick" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="SIM" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Battery" Type="System.String" DbType="NVarChar(50)" CanBeNull="true" />
      <Column Name="Details" Type="System.String" DbType="NVarChar(2000)" CanBeNull="true" />
      <Association Name="Manufacturer_Product" Member="Manufacturer" ThisKey="ID_Manufacturer" OtherKey="Id_Manufacturer" Type="Manufacturer" IsForeignKey="true" />
    </Type>
  </Table>
</Database>